### ISSUE TITLE
Dance to the music

### ISSUE THREAD

**Issue by MajaLinder** [DIT112-V21/group-12#40]
### User Story
As an application car driver I want to be able to pick a song so that the car can dance to the beat of my chosen song.
***
### Acceptance Criteria

- The car can dance to the beat of a song in standard 4/4 time.
- The car can dance to the beat of a song that is not varying in tempo throughout the song.
- The user can only select one song from the applications external/internal media library that the car can perform a dance in sync with the song's tempo.
***

**Sub-tasks**

- [x] Connect the application to an external music library.

- [x] Create the user interface in the application where the user can select any given song.

- [x] Extract the tempo from any given song.

~Make the car's speed move in sync with the given song.~

**Comment by b4rdha** [comment]
We were unable to pass the detected tempo as input for the speed of the dancing car, due to multithreading issues which we were unable to tackle in java on the remaining time. Thus we decided not to implement it and only have music retrieved, with song info and playback position.
